apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: helm-nats
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: '>=v1.1.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: Installs the official NATS Helm chart for high-speed cloud native messaging.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # helm-nats

    Installs the official NATS Helm chart using Crossplane and the Helm provider.
    NATS is a high-performance cloud native messaging system with JetStream support.
  repository: ghcr.io/hops-ops/helm-nats
  source: github.com/hops-ops/helm-nats
